
camera:
  # Best mode is 4, which gives full field of view at 4:3 aspect ratio
  # and 2x2 binning, resulting in an area of 1296x972
  sensor_mode: 4
  width: 1296
  height: 972
  framerate: 15
  bitrate: 2000000  # 2Mbps is a high quality stream for 10 fps HD video
  hflip: True       # Because camera is mounted upside down
  vflip: True

staging_dir: "./output"    # Seems to be faster to write to SD card
final_dir: "/media/videos" # But USB stick has more space

seconds_pre: 20
seconds_post: 60

per_block_threshold: 50    # Motion vector for a single block in a frame must exceed this value
num_threshold_blocks: 10   # At least this many motion vector blocks must have met the `per_block_threshold`
per_frame_threshold: 1500  # Sum of all motion vectors in a frame must exceed this value
per_block_upper_bound: 100    # This is the highest we expect the motion vector per block to be. Used for graph scaling.
per_frame_upper_bound: 50000  # This is the highest we expect the sum of all vectors per frame to be. Used for graph scaling.
scale_boost: 20            # How much to boost lower values in log-scaled graphs. 5 = mild, 10 = medium, 50 = strong, 100 = very strong

web_port: 8080